id: agent-io
hostname: localhost

huri:
  hostname: localhost
  router:
    port: 3000
  event-proxy:
    xsub: 5555
    xpub: 5556
  log-puller:
    port: 8008

forwarder-proxy:
  down-xsub: 6665
  up-xpub: 6666

logging: INFO

modules:
  inp:
    name: INP
    logging: INFO
  out:
    name: OUT
    logging: INFO
  mod:
    name: MOD
    logging: INFO
  rag:
    name: RAG
    args:
      model: deepseek-v2:16b
    logging: INFO
