# HuRI websocket server url
huri_url: ws://localhost:8000/session

# Define interface to be used's import path
interface_path: src.interfaces.cli_interface:cli_interface

# Define senders to be used and their custom args
senders:
  # sender tag can be anything
  example:
    # sender name must be in the list of available ClientSender in chosen Interface (Interface.get_senders)
    name: my_sender
    # topic the sender will send to HuRI, it must match output_type event data structure
    topic: my_event
    # if my_sender init with "model", "sample_rate" and "refresh_rate" params, they can be customized here
    args:
      refresh_rate: infinite

# Define hooks to be used and their custom args
hooks:
  # hook tag can be anything
  example:
    # hook name must be in the list of available ClientHook in chosen Interface (Interface.get_senders)
    name: my_hook
    # topics the hook will process from HuRI, it must match input_type event data structure
    topics: [my_event, llm_response]
    # if my_hook init with "model", "sample_rate" and "refresh_rate" params, they can be customized here
    args:
      sample_rate: 0
      no: beat

# Define module to be used and their custom args
modules:
  # module tag can be anything
  example:
    # module name must be in the list of available module in HuRI's instance (src.modules.modules:get_modules)
    name: my_module
    # if my_module init with "model", "sample_rate" and "hello" params, they can be customized here
    args:
      hello: world
