apiVersion: v2
name: huri
description: HuRI service powered by Ray Serve on KubeRay
type: application
version: 0.1.0
appVersion: "2.52.0"
keywords:
  - ray
  - kuberay
  - ray-serve
  - robotics
  - hri
maintainers:
  - name: Sentience Robotics

dependencies:
  - name: kuberay-operator
    version: "1.6.0"
    repository: "https://ray-project.github.io/kuberay-helm/"
    condition: kuberay.install
